name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: search
    attributes:
      label: Search before posting
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this feature relate to?
      options:
        - New Example
        - New Workflow Guide
        - Documentation Improvement
        - Tool Enhancement
        - Automation Feature
        - Community Feature
        - Performance Improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: |
        Currently, when I try to..., I encounter...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        I would like to see...
        This would work by...
        It should include...
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Target Users
      description: Who would benefit from this feature?
      multiple: true
      options:
        - Beginners
        - Intermediate developers
        - Advanced developers
        - Team leads
        - DevOps engineers
        - AI/ML practitioners
        - Enterprise users
        - All users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (Nice to have)
        - Medium (Would improve my workflow)
        - High (Important for my use case)
        - Critical (Blocking my adoption)
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases or scenarios where this feature would be helpful
      placeholder: |
        Use Case 1: When working on...
        Use Case 2: During the process of...
        Use Case 3: For teams that...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work (mockups, code samples, etc.)
      placeholder: |
        Example command:
        ```bash
        codex "your example here"
        ```
        
        Expected output:
        ```
        Generated code example
        ```

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions? What are the pros/cons?
      placeholder: |
        Alternative 1: ...
        Pros: ...
        Cons: ...

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (1-2 days)
        - Medium (1 week)
        - Complex (2-4 weeks)
        - Very Complex (1+ months)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria
      description: How would we know this feature is successful?
      placeholder: |
        - Users can successfully...
        - Performance improves by...
        - Documentation includes...
        - Community adoption reaches...

  - type: checkboxes
    id: related_features
    attributes:
      label: Related Features
      description: Would this feature work well with or depend on other features?
      options:
        - label: This builds on existing examples
        - label: This requires new workflow guides
        - label: This needs documentation updates
        - label: This affects the benchmark system
        - label: This impacts community features

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references that would help
      placeholder: |
        References:
        - Similar feature in other tools: ...
        - Related documentation: ...
        - Community discussions: ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Interest
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to implement this feature
        - label: I can help with design/planning
        - label: I can provide testing and feedback
        - label: I can help with documentation
        - label: I can provide examples and use cases